apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: chatbot-test-app-60
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/mvaldron-rhdh/chatbot-test-app-60:213bfe0785543974282be74aa9d9b1fec318e3d6@sha256:9afa20684322f1875bd485e16fc4e56b5f0e49df61a76de88371bb01ed8b2265 # use pre-built to bootstrap
          name: app-inference
